refactored scripts

diff --git a/home/.chezmoitemplates/install-arch-packages b/home/.chezmoitemplates/install-arch-packages
--- a/home/.chezmoitemplates/install-arch-packages
+++ b/home/.chezmoitemplates/install-arch-packages
@@ -4,14 +4,13 @@
 # {{- 	$needed = without $needed $installed -}}
 # {{- end -}}
 # {{- if $needed }}
-    info "Installing from # {{ get . "bin" }}: # {{$needed}}"
-    # {{ get . "cmd" }} # {{ $needed | join " " }} >/dev/null
-
-    if [ $? -ne 0 ]; then
-        error "Failed to install packages."
-    else
-        success "Finished install."
-    fi
+info "Installing from # {{ get . "bin" }}: # {{$needed}}"
+# {{ get . "cmd" }} # {{ $needed | join " " }} >/dev/null
+if [ $? -ne 0 ]; then
+  error "Failed to install packages."
+else
+  success "Finished install."
+fi
 # {{- else }}
-    info "Packages from # {{ get . "bin" }} already installed."
+info "Packages from # {{ get . "bin" }} already installed."
 # {{- end -}}
